# Generated by Django 4.0.3 on 2022-04-16 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_datecomplited_alter_todo_important'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='datecomplited',
            new_name='datecompleted',
        ),
    ]
